# Generated by Django 3.2.4 on 2021-07-27 10:16

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(db_index=True, max_length=500), blank=True, null=True, size=None),
        ),
    ]
