# Generated by Django 3.2.4 on 2021-07-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='enum_answer',
            new_name='option_answer',
        ),
    ]
